# 
name: "runner-dr"
description: |-
  Runs a few debug/triaging commands on a runner to attempt to provide useful
  diagnostics to ... well, you. "The Doctor is in."
runs:
  using: "composite"
  steps:

    - shell: bash
      id: diagnostics
      run: "#diagnostics.\nbash ${{github.action_path}}/diagnose.bash"

    - shell: bash
      run: "#print diagnostics output.\njq -CSer '.' <<'EOF'\n${{ toJSON(steps.diagnostics.outputs) }}\nEOF\n"

    - {run: "#print runner.*\njq -SreC '.' <<'__JSON_DATA__'\n${{ toJSON(runner) }}\n__JSON_DATA__\n", shell: bash}
    - {run: "#print github.*\njq -SreC '.' <<'__JSON_DATA__'\n${{ toJSON(github) }}\n__JSON_DATA__\n", shell: bash}

outputs:
  outcome: 
    description: "outcome (usually success; sometimes failure)"
    value: ${{steps.diagnostics.outcome}} 
  hostname: 
    description: "runner's hostname"
    value: ${{steps.diagnostics.outputs.hostname}} 
  cpu: 
    description: "runner's hostname"
    value: ${{steps.diagnostics.outputs.cpu}} 
