name: "demo"
concurrency: { group: "${{ github.workflow }}-${{ github.event_name }}" }
permissions: 
  contents: read
  pull-requests: read
  packages: write

on:
  workflow_dispatch:
  schedule: [{ cron: "0 0 * * *" }]
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - {name: "checkout the code.", uses: "actions/checkout@v2"}
      - {name: "execute this action.", uses: "./."}
